name: PHP

on:
  schedule:
    - cron: '5,15,25,35,45,55 * * * *'
#  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.KEY }}

    - name: Run PHP Scrape
      run: php updater.php

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updating Files
#        branch: Auto-Commit-Branch
        push_options: --force
